version: '3'
services:
  student_compass_postgressql:
    image: postgres:13
    volumes:
      - ../initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-postgres}
      - POSTGRES_DB=student_compass
    ports:
      - "5433:5432"
    restart: always
