spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_compass
    username: root
    password: 6363
    driver-class-name: org.postgresql.Driver
#  flyway:
#    user: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/system_philharmonic_database}
#    baselineOnMigrate: true

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

