INSERT INTO public.subject_name (id, name) VALUES (1, 'ДГМА');
INSERT INTO public.subject_name (id, name) VALUES (2, 'Алгебра');
INSERT INTO public.subject_name (id, name) VALUES (3, 'Русский язык');
INSERT INTO public.subject_name (id, name) VALUES (4, 'История');
INSERT INTO public.subject_name (id, name) VALUES (5, 'Информатика');
INSERT INTO public.subject_name (id, name) VALUES (6, 'ОПП');
INSERT INTO public.subject_name (id, name) VALUES (7, 'C++');
INSERT INTO public.subject_name (id, name) VALUES (8, 'Java');
INSERT INTO public.subject_name (id, name) VALUES (9, 'Математический анализ');
INSERT INTO public.subject_name (id, name) VALUES (10, 'Дискретная математика');
INSERT INTO public.subject_name (id, name) VALUES (11, 'Философия');
INSERT INTO public.subject_name (id, name) VALUES (12, 'Экономика');